- name: Remove nginx (when required)
  hosts: all
  tasks:
    - name: Stop nginx when present
      service:
        name: nginx
        state: stopped
        enabled: false
      ignore_errors: yes

- name: Setup Postgresql
  hosts: all

  roles:
    - name: geerlingguy.postgresql
    - name: geerlingguy.apache
    - name: geerlingguy.php
    - name: adminer
